name: "Build plugin and loader"
on:
  push:
jobs:
  build_windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Dowload IDA SDK
        shell: cmd
        env:
          IDA_SDK: ${{ secrets.DOWNLOAD_LINK_IDA_SDK }}
          PASSWORD: ${{ secrets.ZIP_PASSWORD }}
        run: |
          cd ..
          curl -J -L "%IDA_SDK%" -o idasdk90.zip
          unzip -P "%PASSWORD%" idasdk90.zip
      - name: Build efiXplorer
        run: |
          mkdir build
          cd build
          cmake .. -DIdaSdk_ROOT_DIR="../../idasdk90" -DHexRaysSdk_ROOT_DIR="../../idasdk90"
          cmake --build . --config Release --parallel
      - uses: actions/upload-artifact@master
        with:
          name: efiXplorer64.dll
          path: build/efiXplorer/Release/efiXplorer64.dll
      - uses: actions/upload-artifact@master
        with:
          name: efiXloader64.dll
          path: build/efiXloader/Release/efiXloader64.dll
  build_linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Dowload IDA SDK
        shell: bash
        env:
          IDA_SDK: ${{ secrets.DOWNLOAD_LINK_IDA_SDK }}
          PASSWORD: ${{ secrets.ZIP_PASSWORD }}
        run: |
          cd ..
          curl -J -L "$IDA_SDK" -o idasdk90.zip
          unzip -P $PASSWORD idasdk90.zip
      - name: Build efiXplorer
        run: |
          mkdir build
          cd build
          cmake .. -DIdaSdk_ROOT_DIR="../../idasdk90" -DHexRaysSdk_ROOT_DIR="../../idasdk90"
          cmake --build . --config Release --parallel
      - uses: actions/upload-artifact@master
        with:
          name: efiXplorer64.so
          path: build/efiXplorer/efiXplorer64.so
      - uses: actions/upload-artifact@master
        with:
          name: efiXloader64.so
          path: build/efiXloader/efiXloader64.so
  build_osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Dowload IDA SDK
        shell: bash
        env:
          IDA_SDK: ${{ secrets.DOWNLOAD_LINK_IDA_SDK }}
          PASSWORD: ${{ secrets.ZIP_PASSWORD }}
        run: |
          cd ..
          curl -J -L "$IDA_SDK" -o idasdk90.zip
          unzip -P $PASSWORD idasdk90.zip
      - name: Build efiXplorer
        run: |
          mkdir build
          cd build
          cmake .. -DIdaSdk_ROOT_DIR="../../idasdk90" -DHexRaysSdk_ROOT_DIR="../../idasdk90"
          cmake --build . --config Release --parallel
      - uses: actions/upload-artifact@master
        with:
          name: efiXplorer64.dylib
          path: build/efiXplorer/efiXplorer64.dylib
      - uses: actions/upload-artifact@master
        with:
          name: efiXloader64.dylib
          path: build/efiXloader/efiXloader64.dylib
